
rbac: false

nodeExporter:
  repo: drud/node-exporter #quay.io/prometheus/node-exporter:v0.15.0
  tag: v0.5.0
  resources:
    requests:
      memory: 30Mi
      cpu: 100m
    limits:
      memory: 50Mi
      cpu: 200m

kubeStateMetrics:
  repo: drud/kube-state-metrics #quay.io/coreos/kube-state-metrics:v1.0.1
  tag: v0.5.0
  resources: {}
  addon:
    repo: drud/addon-resizer #gcr.io/google_containers/addon-resizer:1.0
    tag: v0.5.0
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 30Mi

grafana:
  repo: drud/grafana #grafana/grafana:4.5.2
  tag: v0.5.0
  adminUser: admin
  adminPass: admin
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  watcher:
    repo: drud/grafana-watcher #quay.io/coreos/grafana-watcher:v0.0.8
    tag: v0.5.0
    resources:
      requests:
        memory: 16Mi
        cpu: 50m
      limits:
        memory: 32Mi
        cpu: 100m

# configuration for the <release-name>-k8s prometheus instance
prometheus:
  k8s:
    resources:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
    # if enabled, alertmanager instance will be created.
    alerts: false
