version: 2
jobs:
  release:
    machine: true
    working_directory: /home/circleci/go/src/github.com/drud/test

    environment:
      GOPATH: /home/circleci/go

    steps:
      - add_ssh_keys:
        fingerprints:
          - "48:55:59:85:76:e8:5c:c5:9c:b7:0d:32:69:b2:89:ed"

      - run: mkdir -p ~/go/src/github.com/drud/test

      - checkout

      - run: make release

      - run: git commit -am "release $(git describe --tags --always --dirty)"
      - run: git tag -fa $(git describe --tags --always --dirty) -m $(git describe --tags --always --dirty)
      - run: git push origin master --tags

workflows:
  version: 2
  release:
    jobs:
      - release: # build on any tag, no branches
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
