version: 2
jobs:
  release:
    machine: true
    working_directory: /home/circleci/go/src/github.com/drud/test

    environment:
      GOPATH: /home/circleci/go

    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:a5:3f:af:f4:cd:a6:31:07:5f:2e:ed:3d:da:40:67"

      - run: mkdir -p ~/go/src/github.com/drud/test

      - checkout

      - run: |
          git checkout master
          export RELEASE=$(git describe)
          make release
          git describe --dirty
          if [ "$RELEASE" == "$(git describe --dirty)" ]; then
            echo "all good, no commit"
            exit 0
          else
            echo "time to commit"
            git config user.name drud && git config user.email accounts@drud.com
            git commit -am "release $RELEASE"
            git tag -fa $RELEASE -m $RELEASE
            git push origin master --tags --force
          fi

workflows:
  version: 2
  release:
    jobs:
      - release: # build on any tag, no branches
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
