version: 2
stages:
  build:
    machine: true
    working_directory: /home/circleci/golang-build-container

    environment:
      GOPATH: /home/circleci/go

    steps:

      - checkout

      # - run: make container && make test

      - deploy:
          command: |
            git fetch --tags
            git tag
            CURRENT_TAG=$(git describe --tags --abbrev=0)
            COMMIT_TAG=$(git describe --tags)
            echo "current tag ${CURRENT_TAG}"
            echo "commit tag ${COMMIT_TAG}"
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CURRENT_TAG}" == "${COMMIT_TAG}" ]; then
              echo "time to push!"
              # docker login -u $DOCKER_USER -p $DOCKER_PASS
              # make push
            fi

# workaround for build on tag push
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
deployment:
  push_on_tag:
    tag: /.*/
    commands:
      - echo "make build trigger on tag push"
